<?php

namespace AppBundle\Repository;

/**
 * MyEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
